### ISSUE TITLE
Dotless should be updated

### ISSUE THREAD

**Issue by ghost** [berfarah/LESS-build-sublime#25]
Some valid LESS syntax is not recognized by the dotless compiler currently in use in the plugin. After updating to 1.3.1.0 (got it from [here](https://github.com/dotless/dotless/downloads)), it works like a charm again.

Example:

``` less
.item2 {
  .item1 + & {
    opacity:0.5;
  }
}
```

Thanks for the great plugin btw.
